//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714jschmitt2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhLog
    {
        public int Id { get; set; }
        public decimal phReading { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
